### ISSUE TITLE
instagram-py stops after half an hour to an hour 

### ISSUE THREAD

**Issue by klapperys** [deathsec/instagram-py#10]
**Select your issue type:** (check at least one)
- [X] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
script stops after half an hour to an hour 
error:
raceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 278, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: HT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.7/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.7/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 278, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('HT'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/instagram-py", line 11, in <module>
    load_entry_point('instagram-py==2.0.7', 'console_scripts', 'instagram-py')()
  File "/usr/lib/python3.7/site-packages/InstagramPy/__init__.py", line 105, in ExecuteInstagramPy
    InstagramPyScript(Parsed.script, PortableService=PortableService).run()
  File "/usr/lib/python3.7/site-packages/InstagramPy/InstagramPyScript.py", line 131, in run
    self.threads[i]['instance'].TryPassword()
  File "/usr/lib/python3.7/site-packages/InstagramPy/InstagramPyInstance.py", line 143, in TryPassword
    self.session.ChangeIPAddress()  # signal tor to change ip
  File "/usr/lib/python3.7/site-packages/InstagramPy/InstagramPySession.py", line 294, in ChangeIPAddress
    'http://httpbin.org/ip').json())['origin']
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 525, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('HT'))

**Ways to Reproduce the issue (optional):**

**Comment by billychan1** [comment]
hi did you ever fix this issue i got the same thing.
