### ISSUE TITLE
TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by firebreed** [deathsec/instagram-py#2]
Installation went well, but received this error when running it for the first time. Your assistance is much appreciated.

```
[+] target account: target_account
[*] password list path: /root/Desktop/instagram-py/password.txt
[ ATTACK STATUS ]
[                          ] [*] Trying... 123456                              

Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 11, in <module>
    load_entry_point('instagram-py==0.3.1', 'console_scripts', 'instagram-py')()
  File "/usr/local/lib/python3.5/dist-packages/instagram_py/__init__.py", line 89, in main
    InjectPassword(current_session , current_line)
  File "/usr/local/lib/python3.5/dist-packages/instagram_py/instagram_bot.py", line 73, in InjectPassword
    message = json.loads(r.content);
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))

TypeError: the JSON object must be str, not 'bytes'
```

**Comment by deathsec** [comment]
i will look into soon , this error will occur sometime!

**Comment by deathsec** [comment]
found the bug its a recent one , my bad!

**Comment by deathsec** [comment]
Hey @firebreed , the bug was fixed and instagram-py v0.3.2 is out , update your current version by executing this simple command!

```
 $ sudo pip3 install instagram-py --upgrade
 $ # thats it nothing else to do!
```

Thank you for reporting this bug!

**Comment by firebreed** [comment]
Issue _seems_ to have been fixed, however, few seconds after it goes through 3-4 passwords, I receive these messages:

```
[*] password list path: password.txt
[ ATTACK STATUS ]
[                          ] [*] Trying... password                           

 Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 11, in <module>
    load_entry_point('instagram-py==0.3.2', 'console_scripts', 'instagram-py')()
  File "/usr/local/lib/python3.5/dist-packages/instagram_py/__init__.py", line 89, in main
    InjectPassword(current_session , current_line)
  File "/usr/local/lib/python3.5/dist-packages/instagram_py/instagram_bot.py", line 65, in InjectPassword
    '.' + urllib.parse.quote(json.dumps(data)))
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```
Please advise.

**Comment by deathsec** [comment]
does this happen every time , is your tor server up and running , because this seems like a connection error and could you post your instapy-config.json which you copied to the location **~/instapy-config.json**

```
 $ cat ~/instapy-config.json # post the output
```

**Comment by deathsec** [comment]
Hey @firebreed i think the issue is fixed , the error maybe a down time in your network or faulty configuration , if you think it is not solved open a new issue!
