### ISSUE TITLE
Bug at start

### ISSUE THREAD

**Issue by A73D4A** [deathsec/instagram-py#20]
**Select your issue type:** (check at least one)
- [1 ] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

**Describe your issue:**
instagram-py
Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 6, in <module>
    from InstagramPy import ExecuteInstagramPy
  File "/usr/local/lib/python2.7/dist-packages/InstagramPy/__init__.py", line 10, in <module>
    from .InstagramPyCLI import InstagramPyCLI
  File "/usr/local/lib/python2.7/dist-packages/InstagramPy/InstagramPyCLI.py", line 138
    end='')
       ^

**Ways to Reproduce the issue (optional):**

**Comment by bird** [comment]
From the readme: `Depends on: python3` and you're using `python2.7`
