### ISSUE TITLE
another error 

### ISSUE THREAD

**Issue by Mehran** [deathsec/instagram-py#23]
**Select your issue type:** (check at least one)
- [x] Bug
- [ ] Question
- [ ] Suggestion
- [ ] Other (please describe):

After while cracking now im Using Script below error

```
Traceback (most recent call last):
  File "/usr/bin/instagram-py", line 29, in <module>
    InstagramPy.ExecuteInstagramPy()
  File "/usr/local/lib/python3.5/dist-packages/InstagramPy/__init__.py", line 95, in ExecuteInstagramPy
    InstagramPyScript(Parsed.script).run()
  File "/usr/local/lib/python3.5/dist-packages/InstagramPy/InstagramPyScript.py", line 120, in run
    self.threads[i]['instance'].TryPassword()
  File "/usr/local/lib/python3.5/dist-packages/InstagramPy/InstagramPyInstance.py", line 143, in TryPassword
    self.session.ChangeIPAddress()  # signal tor to change ip
  File "/usr/local/lib/python3.5/dist-packages/InstagramPy/InstagramPySession.py", line 294, in ChangeIPAddress
    'https://icanhazip.com').content.rstrip().decode()
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

```
**Ways to Reproduce the issue (optional):**

**Comment by deathsec** [comment]
hmm.. will see later

**Comment by deathsec** [comment]
it seems like you are you using Instagram-Py Scripting

**Comment by deathsec** [comment]
I think I should get rid of **https://icanhazip.com** all together to stop this error!

**Comment by deathsec** [comment]
@Mehran you should see the README again!
