### ISSUE TITLE
perfect program but too slow

### ISSUE THREAD

**Issue by Litx1** [deathsec/instagram-py#26]
hi,
I'm testing your programs (instagram.py) and he work perfectly but he is slower than 512 password at a time, although I've wrote -m 0 to select 32 bot it should takes more than an hour but with 512 password at a time it should takes 7 second
 Did I wrote something wrong or my pc is too slow

**Comment by botis0** [comment]
Hello, how did you make it faster than 1 password every 2 seconds? mine is very slow

**Comment by analjesus** [comment]
@kalibeginner For the love of AnalGod, tell us what you did to multithread.

AnalJesus

**Comment by amirovo** [comment]
@analjesus do you know how to solve this?
Connection to host failed , check your connection and tor configuration :: SOCKSHTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fc3b0869bd0>: Failed to establish a new connection: 0x06: TTL expired'))

**Comment by amirovo** [comment]
@kalibeginner do you know how to solve this? 
Connection to host failed , check your connection and tor configuration :: SOCKSHTTPConnectionPool(host='httpbin.org', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSConnection object at 0x7fc3b0869bd0>: Failed to establish a new connection: 0x06: TTL expired'))

**Comment by analjesus** [comment]
Change InstagramPySession.py, ~line 145 from: 
`try:
            self.bot.get(
                "{}si/fetch_headers/?challenge_type=signup&guid={}".format(
                    self.api_url, str(uuid.uuid4()).replace('-', ''))
            )
            self.magic_cookie = self.bot.cookies['csrftoken']
        except KeyboardInterrupt:
            self.cli.ReportError(
                "cannot get the magic cookie , aborted by the user")
        except (BaseException, Exception) as err:
            self.cli.ReportError(err)   `

to this:
` try:                                                                                                                                                                                                                                                                               retry = Retry(connect=5, backoff_factor=0.5)                                                                                                                                                                                                                                   adapter = HTTPAdapter(max_retries=retry)
            self.bot.mount('http://', adapter)                                                                                                                                                                                                                                             self.bot.mount('https://', adapter)
            self.bot.get(
                "{}si/fetch_headers/?challenge_type=signup&guid={}".format(
                    self.api_url, str(uuid.uuid4()).replace('-', ''))
            )                                                                                                                                                                                                                                                                              self.magic_cookie = self.bot.cookies['csrftoken']
        except KeyboardInterrupt:                                                                                                                                                                                                                                                          self.cli.ReportError(                                                                                                                                                                                                                                                              "cannot get the magic cookie , aborted by the user")                                                                                                                                                                                                                                                   except (BaseException, Exception) as err:                                                                                                                                                                                                                                          self.cli.ReportError(err)      `

Will need to include these imports:
from requests.adapters import HTTPAdapter                                                                                                                                                                                                                                      from requests.exceptions import Timeout, ConnectionError

**Comment by amirovo** [comment]
@analjesus i did it but not working 

Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 6, in <module>
    from InstagramPy import ExecuteInstagramPy
  File "/usr/local/lib/python3.7/dist-packages/InstagramPy/__init__.py", line 11, in <module>
    from .InstagramPySession import InstagramPySession, DEFAULT_PATH
  File "/usr/local/lib/python3.7/dist-packages/InstagramPy/InstagramPySession.py", line 147
    try: retry = Retry(connect=5, backoff_factor=0.5) adapter = HTTPAdapter(max_retries=retry) self.bot.mount('http://', adapter) self.bot.mount('https://', adapter) self.bot.get( "{}si/fetch_headers/?challenge_type=signup&guid={}".format( self.api_url, str(uuid.uuid4()).replace('-', '')) ) self.magic_cookie = self.bot.cookies['csrftoken'] except KeyboardInterrupt: self.cli.ReportError( "cannot get the magic cookie , aborted by the user") except (BaseException, Exception) as err: self.cli.ReportError(err)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
IndentationError: unindent does not match any outer indentation level

**Comment by analjesus** [comment]
You need to match indenting. 

![image](https://user-images.githubusercontent.com/61102325/77781551-25024880-702c-11ea-955c-bde841559dd3.png)

**Comment by amirovo** [comment]
@analjesus **i still get errors like** 
Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 6, in <module>
    from InstagramPy import ExecuteInstagramPy
  File "/usr/local/lib/python3.7/dist-packages/InstagramPy/__init__.py", line 11, in <module>
    from .InstagramPySession import InstagramPySession, DEFAULT_PATH
  File "/usr/local/lib/python3.7/dist-packages/InstagramPy/InstagramPySession.py", line 147
    try:
    ^
IndentationError: unexpected indent

just email me your InstagramPySession.py :arashidi404@gmail.com
**thanks**

**Comment by folektoras** [comment]
@analjesus hey mate! Did you get it to work? I actually used the same code as you wrote it, with correct indents and is still throwing the same
<img width="793" alt="Screenshot 2020-07-13 at 17 16 08" src="https://user-images.githubusercontent.com/25661926/87314991-96f39480-c52c-11ea-9371-9d408fbffe3b.png">
 error :/

**Comment by armin1384-alt3** [comment]
pls help me guys it always said fail....

**Comment by runport** [comment]
fatal error:: unable to send request to instagram :: SOCKSHTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/accounts/login/ (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fdf41aa9ad0>: Failed to establish a new connection: Connection closed unexpectedly'))

**Comment by runport** [comment]
Started @ 2022-11-27 22:02:51.625003
fatal error:: SOCKSHTTPSConnectionPool(host='i.instagram.com', port=443): Max retries exceeded with url: /api/v1/si/fetch_headers/?challenge_type=signup&guid=33f34ae418af4835b7c8dd858e064937 (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0xb592b490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
