### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by Adrwaan** [deathsec/instagram-py#75]
When following the steps described on the installation page on github, instagram-py does not install, it appears that something is going wrong in 'requests'.

Already tried:
 * Remove requests and reinstall
 * Use pip3 and pip
 * And I downloaded the necessary packages before trying to install instagram-py

The error is as follows:
```
Collecting instagram-py
  Using cached instagram-py-2.0.7.tar.gz (31 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_yqe2pyf\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_yqe2pyf\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_yqe2pyf\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_yqe2pyf\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-lct7823i\instagram-py_bce61f5bb4ef405a9ffda4864ec4a843\InstagramPy\__init__.py", line 11, in <module>
          from .InstagramPySession import InstagramPySession, DEFAULT_PATH
        File "C:\Users\user\AppData\Local\Temp\pip-install-lct7823i\instagram-py_bce61f5bb4ef405a9ffda4864ec4a843\InstagramPy\InstagramPySession.py", line 11, in <module>
          import requests
      ModuleNotFoundError: No module named 'requests'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by rishy05** [comment]
Facing the same issue. Found any solution?

**Comment by klgor1803** [comment]
clone the repo
copy the folder InstagramPy to /usr/lib/python3
copy the bin/instagram-py to /usr/bin
chmod +x /usr/bin/instagram-py

**Comment by Adrwaan** [comment]
@Klgor1803 This occurs on Windows, which is why the paths you say do not exist.

**Comment by Akastha68** [comment]
Run **pip install requests**
