### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by ghost** [deathsec/instagram-py#9]
**Select your issue type:** (check at least one)
- [ ] Bug
- [ ] Question
- [ ] Suggestion
- [x ] Other (please describe):

**Describe your issue:**
Traceback (most recent call last):
  File "/usr/local/bin/instagram-py", line 7, in <module>
    from InstagramPy import ExecuteInstagramPy
  File "/usr/local/lib/python2.7/dist-packages/InstagramPy/__init__.py", line 10, in <module>
    from .InstagramPyCLI import InstagramPyCLI
  File "/usr/local/lib/python2.7/dist-packages/InstagramPy/InstagramPyCLI.py", line 138
    end='')

**Ways to Reproduce the issue (optional):**
instagram-py --create-configuration

**Comment by Har0ldf1nch** [comment]
You should use pip3 for installing. Not pip.

**Comment by onkar1720** [comment]
I tried installing pip3 
but i get this:
`root@kali:~# apt-get install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpython3-dev libpython3.5-dev python3-cffi-backend python3-crypto
  python3-cryptography python3-dev python3-idna python3-keyring
  python3-keyrings.alt python3-secretstorage python3-setuptools python3-wheel
  python3.5-dev
Suggested packages:
  python3-crypto-dbg python-crypto-doc python-cryptography-doc
  python3-cryptography-vectors libkf5wallet-bin python3-pykde4
  python-secretstorage-doc python-setuptools-doc
The following NEW packages will be installed:
  libpython3-dev libpython3.5-dev python3-cffi-backend python3-crypto
  python3-cryptography python3-dev python3-idna python3-keyring
  python3-keyrings.alt python3-pip python3-secretstorage python3-setuptools
  python3-wheel python3.5-dev
0 upgraded, 14 newly installed, 0 to remove and 61 not upgraded.
Need to get 39.1 MB of archives.
After this operation, 56.7 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://http.kali.org/kali kali-rolling/main i386 libpython3.5-dev i386 3.5.3-1
  404  Not Found
Err:2 http://http.kali.org/kali kali-rolling/main i386 libpython3-dev i386 3.5.3-1
  404  Not Found
Err:3 http://http.kali.org/kali kali-rolling/main i386 python3-cffi-backend i386 1.9.1-2
  404  Not Found
Err:4 http://http.kali.org/kali kali-rolling/main i386 python3-crypto i386 2.6.1-7
  404  Not Found
Err:5 http://http.kali.org/kali kali-rolling/main i386 python3-idna all 2.2-1
  404  Not Found
Err:6 http://http.kali.org/kali kali-rolling/main i386 python3-setuptools all 33.1.1-1
  404  Not Found
Err:7 http://http.kali.org/kali kali-rolling/main i386 python3-cryptography i386 1.7.1-2
  404  Not Found
Err:8 http://http.kali.org/kali kali-rolling/main i386 python3.5-dev i386 3.5.3-1
  404  Not Found
Err:9 http://http.kali.org/kali kali-rolling/main i386 python3-dev i386 3.5.3-1
  404  Not Found
Err:11 http://http.kali.org/kali kali-rolling/main i386 python3-keyring all 10.1-1
  404  Not Found
Err:12 http://http.kali.org/kali kali-rolling/main i386 python3-keyrings.alt all 1.3-1
  404  Not Found
Err:13 http://http.kali.org/kali kali-rolling/main i386 python3-pip all 9.0.1-2
  404  Not Found
Err:14 http://http.kali.org/kali kali-rolling/main i386 python3-wheel all 0.29.0-2
  404  Not Found
Get:10 http://mirrors.neusoft.edu.cn/kali kali-rolling/main i386 python3-secretstorage all 2.3.1-2 [14.2 kB]
Fetched 14.2 kB in 8s (1,732 B/s)                         
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python3.5/libpython3.5-dev_3.5.3-1_i386.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python3-defaults/libpython3-dev_3.5.3-1_i386.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python-cffi/python3-cffi-backend_1.9.1-2_i386.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python-crypto/python3-crypto_2.6.1-7_i386.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python-idna/python3-idna_2.2-1_all.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python-setuptools/python3-setuptools_33.1.1-1_all.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python-cryptography/python3-cryptography_1.7.1-2_i386.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python3.5/python3.5-dev_3.5.3-1_i386.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python3-defaults/python3-dev_3.5.3-1_i386.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python-keyring/python3-keyring_10.1-1_all.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/k/keyrings.alt/python3-keyrings.alt_1.3-1_all.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/p/python-pip/python3-pip_9.0.1-2_all.deb  404  Not Found
E: Failed to fetch http://http.kali.org/kali/pool/main/w/wheel/python3-wheel_0.29.0-2_all.deb  404  Not Found
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
`

**Comment by Har0ldf1nch** [comment]
@onkar1720  so that means you change your kali source links. It should be installed.
